const enProjects: { [key: string]: string } = {
    "1": 'Poznaj Mikołaja Kopernika, is a website created for the "Szlakiem Mikołaja Kopernika" competition. It has three modules: articles, forum and games. I won second place for this project, thus winning 1500 PLN. It is no longer hosted anywhere, as it would be hard for me to get clients for this project. However, it taught me a lot about web development and the knowledge gained from creating it still helps today.',
    "2": 'Maturzystnie is an app and website created for the national competition "Hack Heroes". There were two people on the team that made Maturzystnie, I was responsible for creating the website and the REST API. This API was needed for my teammate to create Android versions of Maturzystnie. The project was awarded a prize worth PLN 1,500. This project is an e-learning platform that allows you to prepare for the matura exam in any subject. We plan to develop this project in the future, as we see potential in it. The competition version of the Maturzystnie website was created in the Django framework.',
    "3": "Bookmark is an Android app that allows you to record the number of pages you've read and create notes and an event planner for books. I used the app to familiarize myself with the Flutter framework and the Firebase platform. I plan to improve the app in the future, because as my skills in Flutter grow, I see a lot of things to improve there. I'm also thinking to create a website where notes and event schedules can be managed from a computer.",
    "4": "Playlist Tools is my first project written using the Vue library. I got the idea for it when I needed to filter my playlists through filters that are not available in the official Spotify app. Playlist Tools has four tools that will allow you to easily modify your playlists and clean them up.",
    "5": "Technik Informatyk is an app that allows you to effectively study for the exams for the title course. The app is only available for Android and was written in Flutter.  It has different learning modes, so the app can adapt to each student's needs. The first version of the app, which received high reviews, was written in a week. After the success of my week-long creation, I decided to completely refactor the app. It now uses a special API where I can add questions and track problems reported by users.",
    "6": "AlgoDebug was created as the master's thesis of my friend, mgr. inż. Marcin Wojdat, a graduate of the Nicolaus Copernicus University in Toruń. Together with the Computer Scientists' Scientific Club, we decided to expand this project, seeing its great potential. Thanks to our determination and readiness to act, we managed to create a complete project under Marcin's supervision. My role was to be involved in building the frontend, as well as occasionally looking into the backend area.",
};

export default enProjects;
